#!/bin/bash
julia --project Examples/FEMSei/VecINonLinShallow.jl \
  --Problem="GalewskiSphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=80 \
  --RefineLevel=5 \
  --Decomp="EqualArea" \
  --OrderFEM=0 \
  --SimTime=0 \
  --SimDays=1 \
  --SimHours=0 \
  --PrintHours=0 \
  --PrintSeconds=1800 \
  --PrintTime=0
