#!/bin/bash
julia --project Examples/FEMSei/ConsNonLinShallow.jl \
  --Problem="GalewskiSphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=60 \
  --RefineLevel=6 \
  --RefineOutput=1 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=0 \
  --SimHours=1 \
  --PrintHours=0 \
  --PrintSeconds=900 \
  --PrintTime=0
