#!/bin/bash
julia --project Examples/FEMSei/VecINonLinShallow.jl \
  --Problem="GalewskiSphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=160 \
  --RefineLevel=5 \
  --RefineOutput=1 \
  --Decomp="EqualArea" \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=6 \
  --SimHours=0 \
  --PrintHours=1 \
  --PrintSeconds=0 \
  --PrintTime=0
