#!/bin/bash
julia --project Examples/FEMSei/ConsNonLinShallow.jl \
  --Problem="GalewskySphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="TriangularSphere" \
  --RefineLevel=3 \
  --Flat=true \
  --nPanel=60 \
  --RefineOutput=1 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=1 \
  --SimHours=0 \
  --PrintHours=1 \
  --PrintSeconds=0 \
  --PrintTime=0
