#!/bin/bash
julia --project Examples/FEMSei/VecINonLinShallow.jl \
  --Problem="GalewskySphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="TriangularSphere" \
  --RefineLevel=6 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=0 \
  --SimHours=12 \
  --PrintHours=0 \
  --PrintMinutes=30 \
  --PrintSeconds=0 \
  --vtkFileName="Galewsky/VecITri" \
  --RefineOutput=1 \
  --PrintTime=0
