#!/bin/bash
julia --project Examples/FEM/VecINonLinShallow.jl \
  --Problem="HaurwitzSphere" \
  --FloatTypeBackend="Float64" \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=160 \
  --Flat=false \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=6 \
  --SimHours=0 \
  --SimMinutes=0 \
  --PrintHours=1 \
  --PrintMinutes=0 \
  --PrintSeconds=0 \
  --vtkFileName="Haurwitz/VecIQuad" \
  --RefineOutput=1 \
  --PrintTime=0
