#!/bin/bash
julia --project Examples/FEMSei/VecINonLinShallow.jl \
  --Problem="HaurwitzSphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="TriangularSphere" \
  --nPanel=60 \
  --RefineLevel=5 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=0 \
  --SimHours=1 \
  --PrintHours=0 \
  --PrintMinutes=1 \
  --PrintSeconds=0 \
  --PrintTime=0

