#!/bin/bash
julia --project Examples/ConsNonLinShallow.jl \
  --Problem="HaurwitzSphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="TriangularSphere" \
  --nPanel=32 \
  --RefineLevel=5 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=1 \
  --SimHours=1 \
  --PrintHours=1 \
  --PrintSeconds=0 \
  --PrintTime=0

