#!/bin/bash
julia --project Examples/FEMSei/ConsNonLinShallow.jl \
  --Problem="HaurwitzSphere" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=60 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=0 \
  --SimHours=1 \
  --PrintHours=0 \
  --PrintSeconds=900 \
  --vtkFileName="Haurwitz/ConsQuad"
  --RefineOutput=1 \
  --PrintTime=0
