#!/bin/bash
julia --project Examples/FEM/ShallowWaterLinKite.jl \
  --Problem="LinearBlob" \
  --FloatTypeBackend="Float64" \
  --NumberThreadGPU=512 \
  --GridForm="Spherical" \
  --GridType="DelaunaySphere" \
  --nPanel=60 \
  --RefineLevel=6 \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=0 \
  --SimHours=2 \
  --PrintHours=0 \
  --PrintSeconds=100 \
  --RefineOutput=1 \
  --PrintTime=0
