#!/bin/bash
julia --project Examples/FEM/ConsNonLinShallow.jl \
  --Problem="ModonCollision" \
  --FloatTypeBackend="Float64" \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=96 \
  --Flat=true \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=100 \
  --SimHours=0 \
  --SimMinutes=0 \
  --PrintDays=1 \
  --PrintHours=0 \
  --PrintMinutes=0 \
  --PrintSeconds=0 \
  --vtkFileName="ModonCollision/ConsQuad" \
  --RefineOutput=1 \
  --PrintTime=0
