#!/bin/bash
julia --project Examples/FEMSei/ConsNonLinShallow.jl \
  --Problem="ModonCollisionExample" \
  --FloatTypeBackend="Float64" \
  --GridForm="Spherical" \
  --GridType="CubedSphere" \
  --nPanel=50 \
  --Flat=false \
  --OrderFEM=1 \
  --SimTime=0 \
  --SimDays=60 \
  --SimHours=0 \
  --SimMinutes=0 \
  --PrintDays=0 \
  --PrintHours=12 \
  --PrintMinutes=0 \
  --PrintSeconds=0 \
  --vtkFileName="ModonCollision/ConsQuad" \
  --RefineOutput=1 \
  --PrintTime=0