function f=PhiBaroWave(x,y,eta,Param)
y=abs(y);

PhiAvg=Param.T0*Param.Grav/Param.Lapse...
  *(1-eta^(Param.Rd*Param.Lapse/Param.Grav));
PhiPrim=Param.u0/2*((Param.f0-Param.beta0*Param.y0)...
  *(y-Param.Ly/2-Param.Ly/(2*pi)*sin(2*pi*y/Param.Ly))...
  +Param.beta0/2*(y*y-Param.Ly*y/pi*sin(2*pi*y/Param.Ly)...
  -Param.Ly*Param.Ly/(pi*pi*2)*cos(2*pi/Param.Ly)-...
  -Param.Ly*Param.Ly/3-Param.Ly*Param.Ly/(pi*pi*2)));
f=PhiAvg+PhiPrim*log(eta)...
  *exp(-(log(eta)/Param.b)^2);
end