function f=TBaroWave(x,y,eta,Param)
y=abs(y);
PhiPrim=Param.u0/2*((Param.f0-Param.beta0*Param.y0)...
  *(y-Param.Ly/2-Param.Ly/(2*pi)*sin(2*pi*y/Param.Ly))...
  +Param.beta0/2*(y*y-Param.Ly*y/pi*sin(2*pi*y/Param.Ly)...
  -Param.Ly*Param.Ly/(pi*pi*2)*cos(2*pi/Param.Ly)-...
  -Param.Ly*Param.Ly/3-Param.Ly*Param.Ly/(pi*pi*2)));
TAvg=Param.T0*eta^(Param.Rd*Param.Lapse/Param.Grav);
f=TAvg+PhiPrim/Param.Rd*(2/Param.b^2*(log(eta))^2-1)...
  *exp(-(log(eta)/Param.b)^2);
end