env:
  JULIA_VERSION: "1.8.5"
  MPI_IMPL: "openmpi"
  OPENMPI_VERSION: "4.1.1"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"

agents:
  config: cpu
  queue: central

steps:
  - label: "init :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - label: "NHHeldSuarezSphere"
    command: "julia --color=yes --project Examples/testNHHeldSuarezSphere.jl"

  - label: "NHBubbleX"
    command: "julia --color=yes --project Examples/testNHBubbleX.jl"

  - label: "NHHill_L"
    command: "julia --color=yes --project Examples/testNHHill_L.jl"

  - label: "NHHill_M"
    command: "julia --color=yes --project Examples/testNHHill_M.jl"

  - label: "NHHillX"
    command: "julia --color=yes --project Examples/testNHHillX.jl"

  - label: "NHHillY"
    command: "julia --color=yes --project Examples/testNHHillY.jl"

  - label: "NHDensityCurrent"
    command: "julia --color=yes --project Examples/testNHDensityCurrent.jl"

  - label: "NHHeldSuarezSphere"
    command: "julia --color=yes --project Examples/testNHHeldSuarezSphere.jl"

  - label: "NHInertiaGravityWave"
    command: "julia --color=yes --project Examples/testNHInertiaGravityWave.jl"

