env:
  JULIA_VERSION: "1.7.0"
  OPENMPI_VERSION: "4.0.4"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

  - wait

  - label: "NHHeldSuarezSphere"
    command: "julia --color=yes --project Examples/testNHHeldSuarezSphere.jl"

  - label: "NHBubbleX"
    command: "julia --color=yes --project Examples/testNHBubbleX.jl"

  - label: "NHHill_L"
    command: "julia --color=yes --project Examples/testNHHill_L.jl"

  - label: "NHHill_M"
    command: "julia --color=yes --project Examples/testNHHill_M.jl"

  - label: "NHHillX"
    command: "julia --color=yes --project Examples/testNHHillX.jl"

  - label: "NHHillY"
    command: "julia --color=yes --project Examples/testNHHillY.jl"

  - label: "NHDensityCurrent"
    command: "julia --color=yes --project Examples/testNHDensityCurrent.jl"

  - label: "NHHeldSuarezSphere"
    command: "julia --color=yes --project Examples/testNHHeldSuarezSphere.jl"

  - label: "NHInertiaGravityWave"
    command: "julia --color=yes --project Examples/testNHInertiaGravityWave.jl"

