function [X,J,dXdx]=JacobiCart(ksi,eta,F,Grid)
n1=size(ksi,1);
n2=size(eta,2);
X=zeros(n1,n2,2);
% P1=Grid.Nodes(F.N(1)).P;
% P2=Grid.Nodes(F.N(2)).P;
% P3=Grid.Nodes(F.N(3)).P;
% P4=Grid.Nodes(F.N(4)).P,
% X1(:,:,1)=P1*(1-ksi)*(1-eta);
X(:,:,1)=0.25*(Grid.Nodes(F.N(1)).P(1).*(1-ksi)*(1-eta)+...
  Grid.Nodes(F.N(2)).P(1).*(1-ksi)*(1+eta)+...
  Grid.Nodes(F.N(3)).P(1).*(1+ksi)*(1+eta)+...
  Grid.Nodes(F.N(4)).P(1).*(1+ksi)*(1-eta));
X(:,:,2)=0.25*(Grid.Nodes(F.N(1)).P(2).*(1-ksi)*(1-eta)+...
  Grid.Nodes(F.N(2)).P(2).*(1-ksi)*(1+eta)+...
  Grid.Nodes(F.N(3)).P(2).*(1+ksi)*(1+eta)+...
  Grid.Nodes(F.N(4)).P(2).*(1+ksi)*(1-eta));

if nargout>2
  dXdx=zeros(n1,n2,2,2);
  dXdx(:,:,1,1)=0.25*(-Grid.Nodes(F.N(1)).P(1)-Grid.Nodes(F.N(2)).P(1)+...
    Grid.Nodes(F.N(3)).P(1)+Grid.Nodes(F.N(4)).P(1)+...
    ( Grid.Nodes(F.N(1)).P(1)-Grid.Nodes(F.N(2)).P(1)+...
    Grid.Nodes(F.N(3)).P(1)-Grid.Nodes(F.N(4)).P(1))*(ones(n1,1)*eta));
  dXdx(:,:,1,2)=0.25*(-Grid.Nodes(F.N(1)).P(1)+Grid.Nodes(F.N(2)).P(1)+...
    Grid.Nodes(F.N(3)).P(1)-Grid.Nodes(F.N(4)).P(1)+... 
    ( Grid.Nodes(F.N(1)).P(1)-Grid.Nodes(F.N(2)).P(1)+...
    Grid.Nodes(F.N(3)).P(1)-Grid.Nodes(F.N(4)).P(1))*(ksi*ones(1,n2)));
  dXdx(:,:,2,1)=0.25*(-Grid.Nodes(F.N(1)).P(2)-Grid.Nodes(F.N(2)).P(2)+...
    Grid.Nodes(F.N(3)).P(2)+Grid.Nodes(F.N(4)).P(2)+...
    ( Grid.Nodes(F.N(1)).P(2)-Grid.Nodes(F.N(2)).P(2)+...
    Grid.Nodes(F.N(3)).P(2)-Grid.Nodes(F.N(4)).P(2))*(ones(n1,1)*eta));
  dXdx(:,:,2,2)=0.25*(Grid.Nodes(F.N(1)).P(2)-Grid.Nodes(F.N(2)).P(2)+...
    Grid.Nodes(F.N(3)).P(2)-Grid.Nodes(F.N(4)).P(2)+...
    ( Grid.Nodes(F.N(1)).P(2)-Grid.Nodes(F.N(2)).P(2)+...
    Grid.Nodes(F.N(3)).P(2)-Grid.Nodes(F.N(4)).P(2))*(ksi*ones(1,n2)));
  J=dXdx(:,:,1,1).*dXdx(:,:,2,2)-dXdx(:,:,1,2).*dXdx(:,:,2,1);
end

end
