#!/bin/bash
julia --project Examples/Driver.jl \
  --Problem="BaroWaveDrySphere" \
  --NumberThreadGPU=512 \
  --FloatTypeBackend="Float64" \
  `#Model `    \
  --NumV=5 \
  --NumTr=2 \
  --RhoTPos=6 \
  --RhoRPos=7 \
  --Equation="CompressibleShallow" \
  --State="DryInternalEnergy" \
  --ModelType="VectorInvariant" \
  --SurfaceScheme="" \
  --Coriolis=true \
  --Upwind=true \
  --HorLimit=false \
  --Microphysics=false \
  --TypeMicrophysics="OneMomentMicrophysicsMoistEquil" \
  --Sedimentation=false \
  --Buoyancy=true \
  --Damping=true \
  --StrideDamp=10000 \
  --Relax=1.0e-3 \
  --Decomp="EqualArea" \
  --SimSeconds=600 \
  --SimDays=0 \
  `#Output `        \
  --PrintSeconds=150 \
  --PrintMinutes=0 \
  --PrintHours=0 \
  --PrintDays=0 \
  --StartAverageDays=100 \
  --Flat=true \
  --dtau=150 \
  --IntMethod="Rosenbrock" \
  --Table="SSP-Knoth" \
  `#Grid `        \
  --GridForm="Spherical" \
  --Stretch=true \
  --StretchType="Exp" \
  --GridType="CubedSphere" \
  --nz=64 \
  --nPanel=32 \
  --H=30000.0 \
  `#Topography `     \
  --TopoS="" \
  `#Discretization `     \
  --OrdPoly=3 \
  --HyperVisc=true \
  --HyperDCurl=2.e15 \
  --HyperDGrad=2.e15 \
  --HyperDDiv=2.e15 \
  --HyperDDivW=0.e15
