function [div]=FDivGrad2Vec(cCG,CG,Param)
nz=Param.Grid.nz;
OP=CG.OrdPoly+1;
NF=Param.Grid.NumFaces;
D1cCG=reshape(...
  CG.DS*reshape(cCG,OP,OP*NF*nz)...
  ,OP,OP,NF,nz);
D2cCG=permute(reshape(...
  CG.DS...
  *reshape(...
  permute(...
  reshape(cCG,OP,OP,NF,nz)...
  ,[2 1 3 4])...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  ,[2 1 3 4]);
gradCG1=Param.dXdxIC(:,:,:,:,1,1).*D1cCG...
  +Param.dXdxIC(:,:,:,:,2,1).*D2cCG;
gradCG2=Param.dXdxIC(:,:,:,:,1,2).*D1cCG...
  +Param.dXdxIC(:,:,:,:,2,2).*D2cCG;
div=(reshape(...
  CG.DW*(reshape(gradCG1.*Param.dXdxIC(:,:,:,:,1,1)...
  +gradCG2.*Param.dXdxIC(:,:,:,:,1,2)...
  ,OP,OP*NF*nz))...
  ,OP,OP,NF,nz)...
  +...
  permute(...
  reshape(...
  CG.DW*reshape(...
  permute(...
  gradCG1.*Param.dXdxIC(:,:,:,:,2,1)...
  +gradCG2.*Param.dXdxIC(:,:,:,:,2,2)...
  ,[2 1 3 4])...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  ,[2 1 3 4]))...
  ./Param.JC;
end
