function [grad1CG,grad2CG]=FGradDiv2VecDSS(v1CG,v2CG,CG,Param)
OP=CG.OrdPoly+1;
NF=Param.Grid.NumFaces;
nz=Param.Grid.nz;
vC1=reshape(...
  CG.DS*reshape(v1CG.*Param.dXdxIC(:,:,:,:,1,1)...
  +v2CG.*Param.dXdxIC(:,:,:,:,1,2)...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  +permute(...
  reshape(...
  CG.DS*reshape(...
  permute(v1CG.*Param.dXdxIC(:,:,:,:,2,1)...
  +v2CG.*Param.dXdxIC(:,:,:,:,2,2)...
  ,[2 1 3 4])...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  ,[2 1 3 4]);

D1cCG=reshape(...
  CG.DW*reshape(vC1,OP,OP*NF*nz)...
  ,OP,OP,NF,nz);
D2cCG=permute(reshape(...
  CG.DW...
  *reshape(...
  permute(vC1...
  ,[2 1 3 4])...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  ,[2 1 3 4]);

gradCG=zeros(OP,OP,NF,nz,2);
gradCG(:,:,:,:,1)=(Param.dXdxIC(:,:,:,:,1,1).*D1cCG...
  +Param.dXdxIC(:,:,:,:,2,1).*D2cCG)...
  ./Param.JC;
gradCG(:,:,:,:,2)=(Param.dXdxIC(:,:,:,:,1,2).*D1cCG...
  +Param.dXdxIC(:,:,:,:,2,2).*D2cCG)...
  ./Param.JC;


grad=zeros(CG.NumG,nz,2);
for iM=1:size(CG.FaceGlob,2)
  grad(reshape(CG.Glob(:,CG.FaceGlob(iM).Ind,:)...
    ,OP*OP*size(CG.FaceGlob(iM).Ind,1),1),:,:)...
    =grad(reshape(CG.Glob(:,CG.FaceGlob(iM).Ind,:)...
    ,OP*OP*size(CG.FaceGlob(iM).Ind,1),1),:,:)...
    +reshape(gradCG(:,:,CG.FaceGlob(iM).Ind,:)...
    ,OP*OP*size(CG.FaceGlob(iM).Ind,1),nz,2);
end
grad(:,:,1)=grad(:,:,1)./CG.M;
grad(:,:,2)=grad(:,:,2)./CG.M;
grad1CG=reshape(grad(reshape(CG.Glob,OP*OP*NF,1),:,1)...
  ,OP,OP,NF,nz);
grad2CG=reshape(grad(reshape(CG.Glob,OP*OP*NF,1),:,2)...
  ,OP,OP,NF,nz);
end
