function [Rot1CG,Rot2CG]=FRotCurl2VecDSS(v1CG,v2CG,CG,Param)
OP=CG.OrdPoly+1;
NF=Param.Grid.NumFaces;
nz=Param.Grid.nz;

vC1=reshape(...
  CG.DS*reshape(Param.dXdxIC(:,:,:,:,1,1).*v2CG...
  -Param.dXdxIC(:,:,:,:,1,2).*v1CG...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  -permute(...
  reshape(...
  CG.DS*reshape(...
  permute(...
  -v2CG.*Param.dXdxIC(:,:,:,:,2,1)...
  +v1CG.*Param.dXdxIC(:,:,:,:,2,2)...
  ,[2 1 3 4])...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  ,[2 1 3 4]);

D1cCG=reshape(...
  CG.DW*reshape(vC1,OP,OP*NF*nz)...
  ,OP,OP,NF,nz);
D2cCG=permute(reshape(...
  CG.DW...
  *reshape(...
  permute(vC1...
  ,[2 1 3 4])...
  ,OP,OP*NF*nz)...
  ,OP,OP,NF,nz)...
  ,[2 1 3 4]);
RotCG=zeros(OP,OP,NF,nz,2);
RotCG(:,:,:,:,2)=(-Param.dXdxIC(:,:,:,:,1,1).*D1cCG...
  -Param.dXdxIC(:,:,:,:,2,1).*D2cCG)...
  ./Param.JC;
RotCG(:,:,:,:,1)=(Param.dXdxIC(:,:,:,:,1,2).*D1cCG...
  +Param.dXdxIC(:,:,:,:,2,2).*D2cCG)...
  ./Param.JC;
Rot=zeros(CG.NumG,nz,2);
for iM=1:size(CG.FaceGlob,2)
  Rot(reshape(CG.Glob(:,CG.FaceGlob(iM).Ind,:)...
    ,OP*OP*size(CG.FaceGlob(iM).Ind,1),1),:,:)...
    =Rot(reshape(CG.Glob(:,CG.FaceGlob(iM).Ind,:)...
    ,OP*OP*size(CG.FaceGlob(iM).Ind,1),1),:,:)...
    +reshape(RotCG(:,:,CG.FaceGlob(iM).Ind,:)...
    ,OP*OP*size(CG.FaceGlob(iM).Ind,1),nz,2);
end

Rot(:,:,1)=Rot(:,:,1)./CG.M;
Rot(:,:,2)=Rot(:,:,2)./CG.M;
Rot1CG=reshape(Rot(reshape(CG.Glob,OP*OP*NF,1),:,1)...
  ,OP,OP,NF,nz);
Rot2CG=reshape(Rot(reshape(CG.Glob,OP*OP*NF,1),:,2)...
  ,OP,OP,NF,nz);
end
