#!/bin/bash
julia --project Examples/DriverCG.jl \
  --Problem="HeldSuarezDrySphere" \
  --NumberThreadGPU=512 \
  --FloatTypeBackend="Float64" \
  `#Model `    \
  --NumV=5 \
  --NumTr=0 \
  --RhoTPos=0 \
  --RhoRPos=0 \
  --pAuxPos=1 \
  --Equation="CompressibleShallow" \
  --State="Dry" \
  --ModelType="VectorInvariant" \
  --SurfaceScheme="" \
  --Coriolis=true \
  --Upwind=true \
  --HorLimit=false \
  --Microphysics=false \
  --TypeMicrophysics="OneMomentMicrophysicsMoistEquil" \
  --Sedimentation=false \
  --Buoyancy=true \
  --Damping=true \
  --Forcing=true \
  --StrideDamp=10000 \
  --Relax=1.0e-3 \
  --Decomp="EqualArea" \
  --SimSeconds=0 \
  --SimDays=10 \
  `#Output `        \
  --PrintSeconds=0 \
  --PrintMinutes=0 \
  --PrintHours=4 \
  --PrintDays=0 \
  --StartAverageDays=100 \
  --Flat=true \
  --OrdPrint=2 \
  --OrdPrintZ=0 \
  --vtkFileName="output/VTK/HeldSuarezDrySphere/CGE32Quad" \
  --dtau=150 \
  --IntMethod="Rosenbrock" \
  --Table="SSP-Knoth" \
  `#Grid `        \
  --GridForm="Spherical" \
  --Stretch=true \
  --StretchType="Exp" \
  --GridType="CubedSphere" \
  --nLon=128 \
  --nLat=57 \
  --LatB=1.3962634015954636 \
  --nz=64 \
  --nPanel=32 \
  --H=30000.0 \
  `#Topography `     \
  --TopoS="" \
  `#Discretization `     \
  --OrdPoly=3 \
  --HyperVisc=true \
  --HyperDCurl=5.e14 \
  --HyperDGrad=5.e14 \
  --HyperDDiv=5.e14 \
  --HyperDDivW=0.e14
