function F=FluxVolumeNonLin(V,Grid,Param)
NX=Param.OrdPolyX+1;
nV=size(V,1);
F=zeros(size(V));
for iF=1:Grid.NumFaces
  FLoc=FluxNonLin(V(:,:,:,iF),iF,Param);
  for iv=1:nV
    F(iv,:,:,iF)=Param.DXS*(...
       reshape(Param.dXdxI(:,:,1,1,iF),NX,NX).*reshape(FLoc(1,iv,:,:),NX,NX)...
      +reshape(Param.dXdxI(:,:,1,2,iF),NX,NX).*reshape(FLoc(2,iv,:,:),NX,NX)...
      +reshape(Param.dXdxI(:,:,1,3,iF),NX,NX).*reshape(FLoc(3,iv,:,:),NX,NX))...
    +( reshape(Param.dXdxI(:,:,2,1,iF),NX,NX).*reshape(FLoc(1,iv,:,:),NX,NX)...
      +reshape(Param.dXdxI(:,:,2,2,iF),NX,NX).*reshape(FLoc(2,iv,:,:),NX,NX)...
      +reshape(Param.dXdxI(:,:,2,3,iF),NX,NX).*reshape(FLoc(3,iv,:,:),NX,NX)...
      )*Param.DXS';
  end
end
end