function F=RiemannNonLin(V,Grid,Param)
NX=Param.OrdPolyX+1;
nV=size(V,1);
uPos=Param.uPos;
vPos=Param.vPos;
wPos=Param.wPos;
hPos=Param.hPos;
F=zeros(nV,NX,Grid.NumEdges);
VLL=zeros(nV,NX);
VRR=zeros(nV,NX);
for iE=1:Grid.NumEdges
  if size(Grid.Edges(iE).F,2)==2
    FE=Grid.Edges(iE).FE(1);
    iF=Grid.Edges(iE).F(1);
    if FE==1
      VLL(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,:,1,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,:,1,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,:,1,iF),NX,1);
      VLL(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,:,1,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,:,1,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,:,1,iF),NX,1);
      VLL(hPos,:)=reshape(V(hPos,:,1,iF),NX,1);
    elseif FE==2
      VLL(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,NX,:,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,NX,:,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,NX,:,iF),NX,1);
      VLL(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,NX,:,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,NX,:,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,NX,:,iF),NX,1);
      VLL(hPos,:)=reshape(V(hPos,NX,:,iF),NX,1);
    elseif FE==3
      VLL(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,:,NX,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,:,NX,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,:,NX,iF),NX,1);
      VLL(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,:,NX,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,:,NX,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,:,NX,iF),NX,1);
      VLL(hPos,:)=reshape(V(hPos,:,NX,iF),NX,1);
    elseif FE==4
      VLL(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,1,:,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,1,:,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,1,:,iF),NX,1);
      VLL(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,1,:,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,1,:,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,1,:,iF),NX,1);
      VLL(hPos,:)=reshape(V(hPos,1,:,iF),NX,1);
    end
    FE=Grid.Edges(iE).FE(2);
    iF=Grid.Edges(iE).F(2);
    if FE==1
      VRR(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,:,1,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,:,1,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,:,1,iF),NX,1);
      VRR(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,:,1,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,:,1,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,:,1,iF),NX,1);
      VRR(hPos,:)=reshape(V(hPos,:,1,iF),NX,1);
    elseif FE==2
      VRR(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,NX,:,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,NX,:,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,NX,:,iF),NX,1);
      VRR(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,NX,:,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,NX,:,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,NX,:,iF),NX,1);
      VRR(hPos,:)=reshape(V(hPos,NX,:,iF),NX,1);
    elseif FE==3
      VRR(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,:,NX,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,:,NX,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,:,NX,iF),NX,1);
      VRR(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,:,NX,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,:,NX,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,:,NX,iF),NX,1);
      VRR(hPos,:)=reshape(V(hPos,:,NX,iF),NX,1);
    elseif FE==4
      VRR(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,1,:,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,1,:,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,1,:,iF),NX,1);
      VRR(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,1,:,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,1,:,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,1,:,iF),NX,1);
      VRR(hPos,:)=reshape(V(hPos,1,:,iF),NX,1);
    end
  else
    %Boundary
    FE=Grid.Edges(iE).FE(1);
    iF=Grid.Edges(iE).F(1);
    if FE==1
      VLL(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,:,1,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,:,1,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,:,1,iF),NX,1);
      VLL(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,:,1,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,:,1,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,:,1,iF),NX,1);
      VLL(hPos,:)=reshape(V(hPos,:,1,iF),NX,1);
      VRR(uPos,:)=-VLL(uPos,:);
      VRR(vPos,:)=VLL(vPos,:); 
      VRR(hPos,:)=VLL(hPos,:); 
    elseif FE==2
      VLL(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,NX,:,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,NX,:,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,NX,:,iF),NX,1);
      VLL(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,NX,:,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,NX,:,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,NX,:,iF),NX,1);
      VLL(hPos,:)=reshape(V(hPos,NX,:,iF),NX,1);
      VRR(uPos,:)=-VLL(uPos,:);
      VRR(vPos,:)=VLL(vPos,:); 
      VRR(hPos,:)=VLL(hPos,:); 
    elseif FE==3
      VRR(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,:,NX,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,:,NX,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,:,NX,iF),NX,1);
      VRR(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,:,NX,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,:,NX,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,:,NX,iF),NX,1);
      VRR(hPos,:)=reshape(V(hPos,:,NX,iF),NX,1);
      VLL(uPos,:)=-VRR(uPos,:);
      VLL(vPos,:)=VRR(vPos,:);
      VLL(hPos,:)=VRR(hPos,:);
    elseif FE==4
      VRR(uPos,:)=Param.N(:,1,iE).*reshape(V(uPos,1,:,iF),NX,1)...
        +Param.N(:,2,iE).*reshape(V(vPos,1,:,iF),NX,1)...
        +Param.N(:,3,iE).*reshape(V(wPos,1,:,iF),NX,1);
      VRR(vPos,:)=Param.T1(:,1,iE).*reshape(V(uPos,1,:,iF),NX,1)...
        +Param.T1(:,2,iE).*reshape(V(vPos,1,:,iF),NX,1)...
        +Param.T1(:,3,iE).*reshape(V(wPos,1,:,iF),NX,1);
      VRR(hPos,:)=reshape(V(hPos,1,:,iF),NX,1);
      VLL(uPos,:)=-VRR(uPos,:);
      VLL(vPos,:)=VRR(vPos,:);
      VLL(hPos,:)=VRR(hPos,:);
    end
  end
  FLoc=RiemannByLMARSNonLin(VLL,VRR,Param);
  F(uPos,:,iE)=Param.N(:,1,iE).*FLoc(uPos,:)'+Param.T1(:,1,iE).*FLoc(vPos,:)';
  F(vPos,:,iE)=Param.N(:,2,iE).*FLoc(uPos,:)'+Param.T1(:,2,iE).*FLoc(vPos,:)';
  F(wPos,:,iE)=Param.N(:,3,iE).*FLoc(uPos,:)'+Param.T1(:,3,iE).*FLoc(vPos,:)';
  F(hPos,:,iE)=FLoc(hPos,:);
  F(1,:,iE)=reshape(F(1,:,iE),NX,1).*Param.VolSurf(:,iE);
  F(2,:,iE)=reshape(F(2,:,iE),NX,1).*Param.VolSurf(:,iE);
  F(3,:,iE)=reshape(F(3,:,iE),NX,1).*Param.VolSurf(:,iE);
  F(4,:,iE)=reshape(F(4,:,iE),NX,1).*Param.VolSurf(:,iE);
end
end